name: Release Framework
permissions:
    contents: write
    statuses: read
    pull-requests: read
    actions: read
    checks: write
on:
    workflow_dispatch:
        inputs:
            tags:
                description: 'Test scenario tags'
                required: true
                type: boolean
    push:
        tags:
            - "*"

jobs:
    generate-xcframework:
        name: Generate XCFramework
        runs-on: macos-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
            LDK_C_BINDINGS_BASE: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/ldk-c-bindings
        steps:
            -   name: Configure Xcode
                uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                uses: ./.github/actions/install-dependencies
                with:
                    destination: ./bindings/artifacts
            -   name: Generate XCFramework
                uses: ./.github/actions/generate-xcframework
            -   name: Create XCFramework artifact
                uses: ./.github/actions/upload-xcframework-artifact
    release:
        name: Publish Release
        runs-on: ubuntu-latest
        needs: [ generate-xcframework ]
        steps:
            -   name: Download Framework Artifact
                uses: actions/download-artifact@v3
                with:
                    name: LightningDevKit
            -   name: Create Release
                uses: softprops/action-gh-release@v1
                with:
                    files: LightningDevKit.xcframework.zip
    bump-release:
        name: Bump Release
        runs-on: ubuntu-latest
        needs: [release]
        steps:
          - name: Download Latest Release
            id: download-release
            uses: robinraju/release-downloader@v1.4
            with:
              latest: true
              fileName: LightningDevKit.xcframework.zip

          - name: Bump SPM Package
            run: |
              checksum=$(swift package compute-checksum LightningDevKit.xcframework.zip)
              sed -i "s/let tag = \"[0-9]*\.[0-9]*\.[0-9]*\"/let tag = \"${{steps.download-release.outputs.tag_name}}\"/g" Package.swift
              sed -i "s/let checksum = \"[a-zA-Z0-9]*\"/let checksum = \""$checksum"\"/g" Package.swift

          - name: Commit and push changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: Update Package.swift for ${{steps.download-release.outputs.tag_name}} release.
